### ISSUE TITLE
Update to CouchDB 1.7.1

### ISSUE THREAD

**Issue by BigBlueHat** [dokku/dokku-couchdb#27]
There are security issues prior to that version that can result in unintentionally becoming a bitcoin miner...among other unexpected wasteful misuses...
https://github.com/apache/couchdb/issues/1088

Cheers!

**Comment by josegonzalez** [comment]
lmao amazing

**Comment by josegonzalez** [comment]
@BigBlueHat we use the image provided by frodenas [here](https://hub.docker.com/r/frodenas/couchdb/~/dockerfile/). Would you be willing to provide a pr that refactors the plugin to use the official image?

**Comment by BigBlueHat** [comment]
@josegonzalez there are official docker images now: https://github.com/apache/couchdb-docker

I'm sadly very new to the dokku world, so I'm not sure where to even start with a PR. However, dokku's been recommended to me for eons (especially by @tilgovi), so I'm overdue on digging in. 😉 

Point me in the right direction, and I'll see what I can do! 😁

**Comment by josegonzalez** [comment]
You can probably follow our readme [usage](https://github.com/dokku/dokku-couchdb#usage) docs and change the image to the official docker image and see if it works, and just report back on any issues. We have a slack (and an irc room I keep meaning to re-link to slack) that I'm active in and you can ask any questions there :)

**Comment by johnwilson** [comment]
I created a [pull request](https://github.com/dokku/dokku-couchdb/pull/28) with the necessary changes

**Comment by josegonzalez** [comment]
This was completed in #28.
