### ISSUE TITLE
What is link

### ISSUE THREAD

**Issue by mijzcx** [dokku/dokku-couchdb#37]
Hi, 

I'm confused of what does link means?
 
Do link to an app means I have to make a nodejs app for example or use pouchdb to use couchdb and there I could use the couchdb outside the box via pouchdb or my custom rest api?

Or does an app created in dokku directly expose the 
couchdb created, that is, without any mapping envolved.

That is if i create `ouch` for couchdb and link to an app `db_couch`
Can I access to dbcouch.mydomain.com directly?

Thanks and Good Day Man!

**Comment by josegonzalez** [comment]
The `link` command is used to link the service to an application, or rather, allow the application to communicate to the service. A network link is created, and we also set an environment variable with the correct value for that service so your app can talk to it.

Services are not exposed publicly by default. If you'd like to expose it on a port, you can do so via the `expose` subcommand. Fronting this with a hostname is not supported by the plugin at this time.
