### ISSUE TITLE
How to update configuration

### ISSUE THREAD

**Issue by knubie** [dokku/dokku-couchdb#43]
Hi, sorry if this is the wrong medium to ask, but what is the recommended way to update configuration settings? The CouchDB guide describes [updating the local.ini](https://docs.couchdb.org/en/2.3.1/config/intro.html), but that seems at odds with the way dokku works, since entering the service doesn't persist file system changes to disk.

I also tried updating via the HTTP API, but the setting I want to change (`daemons/compaction_daemon`) is blacklisted for change via the API.

**Comment by josegonzalez** [comment]
We currently mount `/opt/couchdb/data` from the host, but no config directory. What is the typical config directory for couchdb, or rather, what is the one the image uses?

**Comment by knubie** [comment]
The config directory is `/opt/couchdb/etc`.

**Comment by knubie** [comment]
@josegonzalez What's the recommended way of mounting that directory??
