### ISSUE TITLE
Usage with official CouchDB images

### ISSUE THREAD

**Issue by almereyda** [dokku/dokku-couchdb#5]
The https://github.com/frodenas/docker-couchdb repository seems pretty unmaintained, while there is [active work being done](https://github.com/docker-library/official-images/pull/1288) to release an official `couchdb` Docker image.

How would one migrate this dokku plugin to that one?

**Comment by almereyda** [comment]
What I found so far is, when ssh'ing into the Dokku host, the `COUCHDB_IMAGE` and `COUCHDB_IMAGE_VERSION` environment variables are being used.
This doesn't work with an alias for dokku on a remote client like `alias dokku='ssh -t dokku@apps.dokku.me'`.

Thus I managed to create a CouchDB image from my `almereyda/geocouch`, but there doesn't seem to be integration of credentials management. It is running as admin party, but successfully connected to my applications container.

**Comment by almereyda** [comment]
The logic from

* https://github.com/frodenas/docker-couchdb/blob/master/scripts/first_run.sh#L10-L18
* https://github.com/frodenas/docker-couchdb/blob/master/scripts/first_run.sh#L23-L29

should therefore be migrated into a fork of

* https://github.com/dokku/dokku-couchdb/blob/master/commands#L44

adapted to

* [ ] the host mounted data volume respecting the location of the filesystem database storage within the soon-to-be-official `couchdb` image
* [ ] followed by `frodenas`' `curl` commands

and https://github.com/dokku/dokku-couchdb/blob/master/config#L2-L3

* [ ] pointing to `couchdb:1.6.1`.

**Comment by josegonzalez** [comment]
@almereyda Do you mind creating a PR with this functionality?

**Comment by almereyda** [comment]
No, I am actually keen on it. But for that we need to adapt @klaemo's
images to accept environment variables containing admin credentials and
further configuration options.

**Comment by josegonzalez** [comment]
Feel free to take a crack at it.

**Comment by klaemo** [comment]
I've a [PR](https://github.com/klaemo/docker-couchdb/pull/46) open to allow config via env vars. Is that what your looking for? It it's okay, I'll merge it and kick off an image update.

**Comment by almereyda** [comment]
As the PR mentioned above has been merged, it seems more easy to update this repository here. I may have time to check this out next week.

**Comment by klaemo** [comment]
yep, the official image now supports env vars https://hub.docker.com/_/couchdb/

**Comment by josegonzalez** [comment]
Closing as no one is interested in working on this. Feel free to submit a PR if you are :)
