### ISSUE TITLE
(Remotely) exposing the port fails

### ISSUE THREAD

**Issue by MorrisJobke** [dokku/dokku-couchdb#9]
I want to remotely access the couchdb container

```
$ ssh dokku@example.org couchdb:expose api
## !     Service is already started
docker: Error response from daemon: failed to create endpoint dokku.couchdb.api.ambassador on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 2409 -j DNAT --to-destination 172.17.0.3:5984 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1).
```

@josegonzalez Is this know? Did I something wrong? If I run this on the server the command exits just fine, but the port is not available on the servers IP. :(

**Comment by josegonzalez** [comment]
Is this still an issue, @MorrisJobke ?

**Comment by MorrisJobke** [comment]
Just, retested and works now :) (I did an update of the plugin some days ago - maybe this fixed it)
